export const COPY = {
  title: 'Hope Invaders',
  tagline: "Max's village has gone dark. Do not let the shadows reach home.",
  start: 'ENTER THE DUNGEONS',
  startHint: 'Click START  ·  Enter  ·  Space',
  docsDesign: 'Design',
  docsMechanics: 'Mechanics',
  docsArt: 'Art',
  controls: 'WASD / arrows: move  |  Click / Space: fire  |  Shift: sink (after Still Water)  |  P: pause',
  license: 'Project Hope — Lumen against the dark',
  tip: 'Do not let the shadows reach the village.',
  gameOver: 'The village goes dark',
  namePrompt: 'Who kept the lantern?',
  nameHint: 'Type a name · Enter to record',
  recordHope: 'RECORD HOPE',
  levelComplete: 'Shard restored',
  lanternArmed: 'Lantern armed — press ENTER again',
  paused: 'PAUSED',
  hopeRestored: 'Hope',
  ammo: ['Wand', 'Lamp', 'Amu'] as const,
  abilityUnlocked: {
    'pool-light': 'Pool Light — every third Wand volley adds a Lamp bolt',
    'still-water': 'Still Water — press SHIFT to sink past harm',
  },
  stillWaterReady: 'SHIFT ready',
  stillWaterActive: 'sinking',
  hope: 'HOPE',
  resolve: 'RSV',
} as const;
